export const COMMON_WORDS = [
  "the", "of", "and", "to", "in", "is", "you", "that", "it", "he",
  "was", "for", "on", "are", "as", "with", "his", "they", "at", "be",
  "this", "have", "from", "or", "one", "had", "by", "word", "but", "not",
  "what", "all", "were", "we", "when", "your", "can", "said", "there", "use",
  "each", "which", "she", "do", "how", "their", "if", "will", "up", "other",
  "about", "out", "many", "then", "them", "these", "so", "some", "her", "would",
  "make", "like", "him", "into", "time", "has", "look", "two", "more", "write",
  "see", "number", "way", "could", "people", "than", "first", "water", "been", "call",
  "who", "oil", "its", "now", "find", "long", "down", "day", "did", "get",
  "come", "made", "may", "part", "over", "new", "sound", "take", "only", "little",
  "work", "know", "place", "year", "live", "back", "give", "most", "very", "after",
  "thing", "our", "just", "name", "good", "sentence", "man", "think", "say", "great",
  "where", "help", "through", "much", "before", "line", "right", "too", "mean", "old",
  "any", "same", "tell", "boy", "follow", "came", "want", "show", "also", "around",
  "form", "three", "small", "set", "put", "end", "does", "another", "well", "large",
  "must", "big", "even", "such", "because", "turn", "here", "why", "ask", "went",
  "men", "read", "need", "land", "different", "home", "us", "move", "try", "kind",
  "hand", "picture", "again", "change", "off", "play", "spell", "air", "away", "animal",
  "house", "point", "page", "letter", "mother", "answer", "found", "study", "still", "learn",
  "should", "world", "high", "every", "near", "add", "food", "between", "own", "below",
] as const;

export const HARD_WORDS = [
  "acquiesce", "aberration", "bureaucracy", "cacophony", "conscientious", "deleterious",
  "ephemeral", "facetious", "gregarious", "hegemony", "idiosyncrasy", "juxtaposition",
  "kaleidoscope", "labyrinthine", "malfeasance", "nomenclature", "obfuscate", "perfunctory",
  "quintessential", "recalcitrant", "sycophant", "tautology", "ubiquitous", "vicissitude",
  "whimsical", "xenophobia", "zealous", "abrogate", "belligerent", "circumlocution",
  "disingenuous", "enervate", "fastidious", "garrulous", "harbinger", "incorrigible",
  "juxtapose", "knavery", "lugubrious", "mendacious", "nefarious", "obstreperous",
  "pernicious", "quixotic", "reticent", "surreptitious", "truculent", "undulate",
  "vexatious", "winsome", "abstemious", "brevity", "convoluted", "deprecate",
  "esoteric", "flagrant", "grandiloquent", "hapless", "impetuous", "jocular",
  "ken", "loquacious", "myriad", "notwithstanding", "obsequious", "parsimonious",
  "quandary", "rescind", "sagacious", "temerity", "unctuous", "vacillate",
  "wanton", "abeyance", "brazen", "conflagration", "demur", "effervescent",
  "fortuitous", "gauche", "harangue", "ignominious", "jettison", "keen",
  "laconic", "morose", "nadir", "obdurate", "paradigm", "querulous",
  "raconteur", "sardonic", "trepidation", "usurp", "vitriolic", "wistful",
  "abnegate", "bombastic", "capricious", "diaphanous", "equivocate", "florid",
  "gratuitous", "hackneyed", "iconoclast", "jaded", "lackadaisical", "mercurial",
] as const;
